# Config file for porter gem

server:
  user: deploy
  domain: <%= domain %>
  dir: /opt/apps/<%= app %>

assets:
  entire_dirs: public/attachments
  excludable_dir: 
  excludable_model: 
  excludable_column: 
  excludable_matches: 
  rsync_options: --verbose --progress --stats --recursive --times --compress

# Example:
# 
# assets:
  # entire_dirs: 
  # excludable_dir: public/attachments
  # excludable_model: Attachment
  # excludable_column: attachable_type
  # excludable_matches: NULL, Design, Item, Placement
  # rsync_options: --verbose --progress --stats --recursive --times --compress