# Config file for porter gem

server:
  user: deploy
  domain: <%= domain %>
  dir: /opt/apps/<%= app %>

# If you want to be able to pull from different environments, and the domains,
# usernames or directories differ, you can delete the catch-all server option 
# above and enable a config for each environment's details like this:
#
# production:
#   user: deploy
#   domain: <%= domain %>
#   dir: /opt/apps/<%= app %>
#
# staging:
#   user: deploy
#   domain: <%= domain %>
#   dir: /opt/apps/<%= app %>

assets:
  entire_dirs: public/attachments
  excludable_dir: 
  excludable_model: 
  excludable_column: 
  excludable_matches: 
  rsync_options: --verbose --progress --stats --recursive --times --compress

# Example:
# 
# assets:
  # entire_dirs: public/campaign public/user
  # excludable_dir: public/attachments
  # excludable_model: Attachment
  # excludable_column: attachable_type
  # excludable_matches: Document Product
  # rsync_options: --verbose --progress --stats --recursive --times --compress